version: '3.8'

services:
  backend:
    build:
      context: ./backend-dotnet
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./storage:/app/storage
    depends_on:
      - ml-service

  frontend:
    build:
      context: ./frontend-angular
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

  ml-service:
    build:
      context: ./ml-service-python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
    environment:
      - PYTHONUNBUFFERED=1

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  storage:
